export const DASHBOARD_PROJECTS = [
  {
    id: 1,
    name: "Breast Cancer Analysis",
    description: "TCGA BRCA 유방암 멀티오믹스 데이터",
    sampleCount: 1226,
    fileCount: 3,
    size: "2.3 GB",
    status: "진행중",
    currentStatus: "진행중",
    createdAt: "2025-10-14",
  },
  {
    id: 2,
    name: "Lung Cancer Study",
    description: "TCGA LUAD/LUSC 폐암 유전체 분석",
    sampleCount: 892,
    fileCount: 2,
    size: "1.8 GB",
    status: "진행중",
    currentStatus: "완료",
    createdAt: "2025-10-13",
  },
  {
    id: 3,
    name: "Pan-Cancer Atlas",
    description: "33개 암종 통합 분석 프로젝트",
    sampleCount: 10967,
    fileCount: 5,
    size: "8.7 GB",
    status: "진행중",
    currentStatus: "대기",
    createdAt: "2025-10-12",
  },
  {
    id: 4,
    name: "Glioblastoma Research",
    description: "GBM 뇌종양 후성유전학 연구",
    sampleCount: 456,
    fileCount: 2,
    size: "980 MB",
    status: "완료",
    currentStatus: "완료",
    createdAt: "2025-10-10",
  },
];
